# Generated by Django 6.0.6 on 2026-06-07 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('input_format', models.CharField(default='csv', max_length=10)),
                ('n_samples', models.IntegerField(blank=True, null=True)),
                ('n_features', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('recommended_metric', models.CharField(blank=True, max_length=100)),
                ('recommended_algorithm', models.CharField(blank=True, max_length=100)),
                ('predicted_ari', models.FloatField(blank=True, null=True)),
                ('meta_features_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('dataset_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(default='csv', max_length=10)),
                ('n_samples', models.IntegerField(blank=True, null=True)),
                ('n_features', models.IntegerField(blank=True, null=True)),
                ('meta_features', models.JSONField(default=dict)),
                ('recommended_metric', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_algorithm', models.CharField(blank=True, max_length=100, null=True)),
                ('top3_algorithms', models.JSONField(default=list)),
                ('hp_intervals', models.JSONField(default=dict)),
                ('predicted_cvi_metric', models.CharField(blank=True, max_length=100, null=True)),
                ('ari_prediction', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvolutionarySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('current_generation', models.IntegerField(default=0)),
                ('total_generations', models.IntegerField(default=10)),
                ('population_size', models.IntegerField(default=40)),
                ('fitness_metric', models.CharField(default='silhouette', max_length=50)),
                ('bandit_strategy', models.CharField(default='ucb1', max_length=20)),
                ('best_fitness', models.FloatField(default=0.0)),
                ('best_pipeline', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evolution', to='clustering.datasetanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_number', models.IntegerField()),
                ('best_pipeline', models.CharField(max_length=255)),
                ('fitness_score', models.FloatField()),
                ('pipelines_evaluated', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='clustering.evolutionarysession')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('company_org', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
