# Generated by Django 6.0.6 on 2026-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0002_update_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusteringtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='evolutionarysession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
